name: Haskell

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            findDirs: find
          - os: macOS-latest
            findDirs: find
          - os: windows-latest
            findDirs: tree
          
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ##exclude:
        #  # GHC 8.8+ only works with cabal v3+
        #  - ghc: 8.8.4
        #    cabal: 2.4.1.0
    

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.10.1'
        cabal-version: '3.12.1.0'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal new-build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test all
    - name: Generate distribution
      run: cabal new-sdist
