name: "4 Letters"
on:
  schedule:
    - cron: "0 2 * * *"
  pull_request:
  push:
  workflow_dispatch:
jobs:
  setup-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
  setup-ssh-key:
    runs-on: ubuntu-latest
    steps:
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  setup-cachix:
    runs-on: ubuntu-latest
    needs: setup-nix
    steps:
    - uses: cachix/cachix-action@v11
      with:
        name: dandart
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  build:
    runs-on: ubuntu-latest
    needs: setup-nix
    steps:
    - run: |
        nix-build
  push-to-cachix:
    runs-on: ubuntu-latest
    needs: [build, setup-cachix]
    steps:
    - run: |
        nix-store -qR --include-outputs $(nix-instantiate shell.nix --add-root result/shell --indirect) | cachix push dandart
  push-to-zhang:
    runs-on: ubuntu-latest
    needs: [build, setup-ssh-key]
    steps:
    - run: |
        nix-store -qR --include-outputs $(nix-instantiate shell.nix --add-root result/shell --indirect) | xargs nix-copy-closure --gzip -s --include-outputs dwd@cache.jolharg.com
